site_name: How to use d4pdf?
theme:
    name: material
    font:
        text: Roboto
    palette:
        primary: green

markdown_extensions:
    - codehilite:
        noclasses: true
        pygments_style: colorful
        linenums: true

markdown_extensions:
    - admonition
    # スーパーフェンス機能の設定
    - pymdownx.superfences